server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: 'jdbc:h2:mem:security'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace